" Name:         enough-colors
" Description:  minimal colorscheme.
" Author:       ycm
" Maintainer:   ycm
" Website:      github.com/ycm
" License:      Public domain
" Last Change:  2024 Dec 06

" Generated by Colortemplate v2.2.3

hi clear
let g:colors_name = 'enough'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)
let s:italics = has('gui_running') || (&t_ZH != '' && &t_ZH != '[7m' && !has('win32'))

hi! link Added diffAdded
hi! link Boolean Constant
hi! link Character Constant
hi! link Changed diffChanged
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Removed diffRemoved
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link Structure Type
hi! link StorageClass Type
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link vimCommentString Comment
hi! link lCursor Cursor

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#000000', '#800000', '#008000', '#808000', '#000080', '#800080', '#008080', '#c0c0c0', '#808080', '#ff0000', '#00ff00', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#ffffff']
  endif
  if get(g:, 'enough_colors_opt_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#bebebe guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#bebebe guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
    hi Terminal guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#282828 gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#282828 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#646464 guibg=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#bebebe guibg=#1e1e1e gui=reverse cterm=reverse
  hi DiffChange guifg=#bebebe guibg=#1e1e1e gui=reverse cterm=reverse
  hi DiffDelete guifg=#bebebe guibg=#1e1e1e gui=reverse cterm=reverse
  hi DiffText guifg=#bebebe guibg=#1e1e1e gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#82b4dc guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#646464 guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi Folded guifg=#b46eb4 guibg=#2d232d gui=italic cterm=italic
  hi IncSearch guifg=#6eb46e guibg=#232d23 gui=NONE cterm=NONE
  hi LineNr guifg=#646464 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi ModeMsg guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi MoreMsg guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi NonText guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi Pmenu guifg=#bebebe guibg=#282828 gui=NONE cterm=NONE
  hi PmenuSbar guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi PmenuSel guifg=#b48c5a guibg=#2d2d23 gui=NONE cterm=NONE
  hi PmenuThumb guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi Question guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi Search guifg=#b48c5a guibg=#2d2d23 gui=NONE cterm=NONE
  hi SignColumn guifg=#bebebe guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi SpellBad guifg=#bebebe guibg=#1e1e1e guisp=#2d2323 gui=NONE cterm=NONE
  hi SpellCap guifg=#bebebe guibg=#1e1e1e guisp=#23232d gui=NONE cterm=NONE
  hi SpellLocal guifg=#bebebe guibg=#1e1e1e guisp=#2d232d gui=NONE cterm=NONE
  hi SpellRare guifg=#bebebe guibg=#1e1e1e guisp=#232828 gui=reverse cterm=reverse
  hi StatusLine guifg=#82b4dc guibg=#23232d gui=NONE cterm=NONE
  hi StatusLineNC guifg=#646464 guibg=#23232d gui=NONE cterm=NONE
  hi StatusLineTerm guifg=#6eb46e guibg=#232d23 gui=NONE cterm=NONE
  hi StatusLineTermNC guifg=#646464 guibg=#232d23 gui=NONE cterm=NONE
  hi TabLine guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi TabLineFill guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi TabLineSel guifg=#bebebe guibg=#1e1e1e gui=NONE cterm=NONE
  hi Title guifg=#bebebe guibg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#646464 guibg=NONE gui=NONE cterm=NONE
  hi Visual guifg=#64b4a0 guibg=#232828 gui=NONE cterm=NONE
  hi VisualNOS guifg=#64b4a0 guibg=#232828 gui=NONE cterm=NONE
  hi WarningMsg guifg=#b48c5a guibg=NONE gui=italic cterm=italic
  hi WildMenu guifg=#b48c5a guibg=#2d2d23 gui=NONE cterm=NONE
  hi Comment guifg=#646464 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#82b4dc guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#b45a5a guibg=NONE gui=italic cterm=italic
  hi Identifier guifg=#bebebe guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#bebebe guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#b45a5a guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#b45a5a guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#bebebe guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#bebebe guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#b46eb4 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#bebebe guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#b45a5a guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#bebebe guibg=NONE gui=underline cterm=underline
  hi! link Quote String
  hi! link CursorColumn CursorLine
  hi! link Number Constant
  hi! link ErrorMsg Error
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#282828 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#bebebe guibg=#1e1e1e gui=bold cterm=bold
  hi! link luaTable Normal
  hi! link jsonKeyword Normal
  hi! link jsonQuote Normal
  hi! link jsonString Normal
  hi! link htmlTag Keyword
  hi! link htmlEndTag Keyword
  hi NERDTreeExecFile guifg=#b46eb4 guibg=NONE gui=NONE cterm=NONE
  hi! link NERDTreeCWD Comment
  hi! link NERDTreeDirSlash Directory
  hi YcmInverse guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link HarpyFileNotFound Error
  hi HarpySelectedFile guifg=#6eb46e guibg=#232d23 gui=NONE cterm=NONE
  hi GenericRedPop guifg=#b45a5a guibg=#2d2323 gui=bold,italic cterm=bold,italic
  hi GenericGreenPop guifg=#6eb46e guibg=#232d23 gui=bold,italic cterm=bold,italic
  hi GenericYellowPop guifg=#b48c5a guibg=#2d2d23 gui=bold,italic cterm=bold,italic
  hi GenericBluePop guifg=#82b4dc guibg=#23232d gui=bold,italic cterm=bold,italic
  hi GenericMagentaPop guifg=#b46eb4 guibg=#2d232d gui=bold,italic cterm=bold,italic
  hi GenericCyanPop guifg=#64b4a0 guibg=#232828 gui=bold,italic cterm=bold,italic
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi WarningMsg gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi Error gui=NONE cterm=NONE
    hi YcmInverse gui=NONE cterm=NONE
    hi GenericRedPop gui=bold cterm=bold
    hi GenericGreenPop gui=bold cterm=bold
    hi GenericYellowPop gui=bold cterm=bold
    hi GenericBluePop gui=bold cterm=bold
    hi GenericMagentaPop gui=bold cterm=bold
    hi GenericCyanPop gui=bold cterm=bold
  endif
else
  " Light background
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#000000', '#800000', '#008000', '#808000', '#000080', '#800080', '#008080', '#c0c0c0', '#808080', '#ff0000', '#00ff00', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#ffffff']
  endif
  if get(g:, 'enough_colors_opt_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#282828 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#282828 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#f0f0f0 gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#ffffff guibg=#282828 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#f0f0f0 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#787878 guibg=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#ffffff guibg=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#ffffff guibg=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#ffffff guibg=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#ffffff guibg=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#0050b4 guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#787878 guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#ffffff guibg=#282828 gui=NONE cterm=NONE
  hi Folded guifg=#783caa guibg=#faebfa gui=italic cterm=italic
  hi IncSearch guifg=#288c1e guibg=#c8f0c8 gui=NONE cterm=NONE
  hi LineNr guifg=#787878 guibg=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#282828 guibg=#f0f0f0 gui=NONE cterm=NONE
  hi PmenuSbar guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#8c8200 guibg=#fafab4 gui=NONE cterm=NONE
  hi PmenuThumb guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi Question guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=#8c8200 guibg=#fafab4 gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi SpecialKey guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#282828 guibg=NONE guisp=#c82828 gui=NONE cterm=NONE
  hi SpellCap guifg=#282828 guibg=NONE guisp=#0050b4 gui=NONE cterm=NONE
  hi SpellLocal guifg=#282828 guibg=NONE guisp=#783caa gui=NONE cterm=NONE
  hi SpellRare guifg=#282828 guibg=NONE guisp=#508c78 gui=reverse cterm=reverse
  hi StatusLine guifg=#0050b4 guibg=#c8dcf0 gui=italic cterm=italic
  hi StatusLineNC guifg=#787878 guibg=#c8dcf0 gui=NONE cterm=NONE
  hi StatusLineTerm guifg=#288c1e guibg=#c8f0c8 gui=italic cterm=italic
  hi StatusLineTermNC guifg=#787878 guibg=#c8f0c8 gui=NONE cterm=NONE
  hi TabLine guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi Title guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#787878 guibg=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#d2e6f0 gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#d2e6f0 gui=NONE cterm=NONE
  hi WarningMsg guifg=#8c8200 guibg=NONE gui=italic cterm=italic
  hi WildMenu guifg=#8c8200 guibg=#fafab4 gui=italic cterm=italic
  hi Comment guifg=#787878 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#0050b4 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#c82828 guibg=NONE gui=italic cterm=italic
  hi Identifier guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#c82828 guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#c82828 guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#783caa guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#c82828 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#282828 guibg=NONE gui=underline cterm=underline
  hi! link Quote String
  hi! link CursorColumn CursorLine
  hi! link Number Constant
  hi! link ErrorMsg Error
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#f0f0f0 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#282828 guibg=#f0f0f0 gui=bold cterm=bold
  hi! link luaTable Normal
  hi! link jsonKeyword Normal
  hi! link jsonQuote Normal
  hi! link jsonString Normal
  hi! link htmlTag Keyword
  hi! link htmlEndTag Keyword
  hi NERDTreeExecFile guifg=#783caa guibg=NONE gui=NONE cterm=NONE
  hi! link NERDTreeCWD Comment
  hi! link NERDTreeDirSlash Directory
  hi YcmInverse guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link HarpyFileNotFound Error
  hi HarpySelectedFile guifg=#288c1e guibg=#c8f0c8 gui=NONE cterm=NONE
  hi GenericRedPop guifg=#c82828 guibg=#fab4b4 gui=bold,italic cterm=bold,italic
  hi GenericGreenPop guifg=#288c1e guibg=#c8f0c8 gui=bold,italic cterm=bold,italic
  hi GenericYellowPop guifg=#8c8200 guibg=#fafab4 gui=bold,italic cterm=bold,italic
  hi GenericBluePop guifg=#0050b4 guibg=#c8dcf0 gui=bold,italic cterm=bold,italic
  hi GenericMagentaPop guifg=#783caa guibg=#faebfa gui=bold,italic cterm=bold,italic
  hi GenericCyanPop guifg=#508c78 guibg=#d2e6f0 gui=bold,italic cterm=bold,italic
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi StatusLine gui=NONE cterm=NONE
    hi StatusLineTerm gui=NONE cterm=NONE
    hi WarningMsg gui=NONE cterm=NONE
    hi WildMenu gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi Error gui=NONE cterm=NONE
    hi YcmInverse gui=NONE cterm=NONE
    hi GenericRedPop gui=bold cterm=bold
    hi GenericGreenPop gui=bold cterm=bold
    hi GenericYellowPop gui=bold cterm=bold
    hi GenericBluePop gui=bold cterm=bold
    hi GenericMagentaPop gui=bold cterm=bold
    hi GenericCyanPop gui=bold cterm=bold
  endif
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'enough_colors_opt_transp_bg', 0)
      hi Normal ctermfg=250 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=250 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=250 ctermbg=234 cterm=NONE
      hi Terminal ctermfg=250 ctermbg=234 cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=250 ctermbg=234 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
    hi CursorLineNr ctermfg=241 ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=250 ctermbg=234 cterm=reverse
    hi DiffChange ctermfg=250 ctermbg=234 cterm=reverse
    hi DiffDelete ctermfg=250 ctermbg=234 cterm=reverse
    hi DiffText ctermfg=250 ctermbg=234 cterm=bold,reverse
    hi Directory ctermfg=110 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=241 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=250 ctermbg=234 cterm=NONE
    hi Folded ctermfg=133 ctermbg=235 cterm=italic
    hi IncSearch ctermfg=71 ctermbg=235 cterm=NONE
    hi LineNr ctermfg=241 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=250 ctermbg=234 cterm=NONE
    hi ModeMsg ctermfg=250 ctermbg=234 cterm=NONE
    hi MoreMsg ctermfg=250 ctermbg=234 cterm=NONE
    hi NonText ctermfg=250 ctermbg=234 cterm=NONE
    hi Pmenu ctermfg=250 ctermbg=235 cterm=NONE
    hi PmenuSbar ctermfg=250 ctermbg=234 cterm=NONE
    hi PmenuSel ctermfg=137 ctermbg=236 cterm=NONE
    hi PmenuThumb ctermfg=250 ctermbg=234 cterm=NONE
    hi Question ctermfg=250 ctermbg=234 cterm=NONE
    hi Search ctermfg=137 ctermbg=236 cterm=NONE
    hi SignColumn ctermfg=250 ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=250 ctermbg=234 cterm=NONE
    hi SpellBad ctermfg=250 ctermbg=234 cterm=NONE
    hi SpellCap ctermfg=250 ctermbg=234 cterm=NONE
    hi SpellLocal ctermfg=250 ctermbg=234 cterm=NONE
    hi SpellRare ctermfg=250 ctermbg=234 cterm=reverse
    hi StatusLine ctermfg=110 ctermbg=235 cterm=NONE
    hi StatusLineNC ctermfg=241 ctermbg=235 cterm=NONE
    hi StatusLineTerm ctermfg=71 ctermbg=235 cterm=NONE
    hi StatusLineTermNC ctermfg=241 ctermbg=235 cterm=NONE
    hi TabLine ctermfg=250 ctermbg=234 cterm=NONE
    hi TabLineFill ctermfg=250 ctermbg=234 cterm=NONE
    hi TabLineSel ctermfg=250 ctermbg=234 cterm=NONE
    hi Title ctermfg=250 ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=241 ctermbg=NONE cterm=NONE
    hi Visual ctermfg=72 ctermbg=235 cterm=NONE
    hi VisualNOS ctermfg=72 ctermbg=235 cterm=NONE
    hi WarningMsg ctermfg=137 ctermbg=NONE cterm=italic
    hi WildMenu ctermfg=137 ctermbg=236 cterm=NONE
    hi Comment ctermfg=241 ctermbg=NONE cterm=italic
    hi Constant ctermfg=110 ctermbg=NONE cterm=NONE
    hi Error ctermfg=131 ctermbg=NONE cterm=italic
    hi Identifier ctermfg=250 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=250 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=131 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=131 ctermbg=NONE cterm=NONE
    hi Operator ctermfg=250 ctermbg=NONE cterm=NONE
    hi Special ctermfg=250 ctermbg=NONE cterm=NONE
    hi String ctermfg=133 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=250 ctermbg=NONE cterm=NONE
    hi Type ctermfg=131 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=250 ctermbg=NONE cterm=underline
    hi! link Quote String
    hi! link CursorColumn CursorLine
    hi! link Number Constant
    hi! link ErrorMsg Error
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=235 cterm=NONE
    hi ToolbarButton ctermfg=250 ctermbg=234 cterm=bold
    hi! link luaTable Normal
    hi! link jsonKeyword Normal
    hi! link jsonQuote Normal
    hi! link jsonString Normal
    hi! link htmlTag Keyword
    hi! link htmlEndTag Keyword
    hi NERDTreeExecFile ctermfg=133 ctermbg=NONE cterm=NONE
    hi! link NERDTreeCWD Comment
    hi! link NERDTreeDirSlash Directory
    hi YcmInverse ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link HarpyFileNotFound Error
    hi HarpySelectedFile ctermfg=71 ctermbg=235 cterm=NONE
    hi GenericRedPop ctermfg=131 ctermbg=235 cterm=bold,italic
    hi GenericGreenPop ctermfg=71 ctermbg=235 cterm=bold,italic
    hi GenericYellowPop ctermfg=137 ctermbg=236 cterm=bold,italic
    hi GenericBluePop ctermfg=110 ctermbg=235 cterm=bold,italic
    hi GenericMagentaPop ctermfg=133 ctermbg=235 cterm=bold,italic
    hi GenericCyanPop ctermfg=72 ctermbg=235 cterm=bold,italic
    if !s:italics
      hi Folded cterm=NONE
      hi WarningMsg cterm=NONE
      hi Comment cterm=NONE
      hi Error cterm=NONE
      hi YcmInverse cterm=NONE
      hi GenericRedPop cterm=bold
      hi GenericGreenPop cterm=bold
      hi GenericYellowPop cterm=bold
      hi GenericBluePop cterm=bold
      hi GenericMagentaPop cterm=bold
      hi GenericCyanPop cterm=bold
    endif
  else
    " Light background
    if get(g:, 'enough_colors_opt_transp_bg', 0)
      hi Normal ctermfg=235 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=235 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=235 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=235 ctermbg=NONE cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=255 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=231 ctermbg=235 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
    hi CursorLineNr ctermfg=243 ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=231 ctermbg=NONE cterm=reverse
    hi DiffChange ctermfg=231 ctermbg=NONE cterm=reverse
    hi DiffDelete ctermfg=231 ctermbg=NONE cterm=reverse
    hi DiffText ctermfg=231 ctermbg=NONE cterm=bold,reverse
    hi Directory ctermfg=26 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=243 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=231 ctermbg=235 cterm=NONE
    hi Folded ctermfg=91 ctermbg=255 cterm=italic
    hi IncSearch ctermfg=28 ctermbg=194 cterm=NONE
    hi LineNr ctermfg=243 ctermbg=NONE cterm=NONE
    hi ModeMsg ctermfg=235 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=235 ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=235 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=235 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=235 ctermbg=255 cterm=NONE
    hi PmenuSbar ctermfg=235 ctermbg=NONE cterm=NONE
    hi PmenuSel ctermfg=100 ctermbg=229 cterm=NONE
    hi PmenuThumb ctermfg=235 ctermbg=NONE cterm=NONE
    hi Question ctermfg=235 ctermbg=NONE cterm=NONE
    hi Search ctermfg=100 ctermbg=229 cterm=NONE
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=235 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=235 ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=235 ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=235 ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=235 ctermbg=NONE cterm=reverse
    hi StatusLine ctermfg=26 ctermbg=153 cterm=italic
    hi StatusLineNC ctermfg=243 ctermbg=153 cterm=NONE
    hi StatusLineTerm ctermfg=28 ctermbg=194 cterm=italic
    hi StatusLineTermNC ctermfg=243 ctermbg=194 cterm=NONE
    hi TabLine ctermfg=235 ctermbg=NONE cterm=NONE
    hi TabLineFill ctermfg=235 ctermbg=NONE cterm=NONE
    hi TabLineSel ctermfg=235 ctermbg=NONE cterm=NONE
    hi Title ctermfg=235 ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=243 ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=254 cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=254 cterm=NONE
    hi WarningMsg ctermfg=100 ctermbg=NONE cterm=italic
    hi WildMenu ctermfg=100 ctermbg=229 cterm=italic
    hi Comment ctermfg=243 ctermbg=NONE cterm=italic
    hi Constant ctermfg=26 ctermbg=NONE cterm=NONE
    hi Error ctermfg=160 ctermbg=NONE cterm=italic
    hi Identifier ctermfg=235 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=235 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=160 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=160 ctermbg=NONE cterm=NONE
    hi Operator ctermfg=235 ctermbg=NONE cterm=NONE
    hi Special ctermfg=235 ctermbg=NONE cterm=NONE
    hi String ctermfg=91 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=235 ctermbg=NONE cterm=NONE
    hi Type ctermfg=160 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=235 ctermbg=NONE cterm=underline
    hi! link Quote String
    hi! link CursorColumn CursorLine
    hi! link Number Constant
    hi! link ErrorMsg Error
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=255 cterm=NONE
    hi ToolbarButton ctermfg=235 ctermbg=255 cterm=bold
    hi! link luaTable Normal
    hi! link jsonKeyword Normal
    hi! link jsonQuote Normal
    hi! link jsonString Normal
    hi! link htmlTag Keyword
    hi! link htmlEndTag Keyword
    hi NERDTreeExecFile ctermfg=91 ctermbg=NONE cterm=NONE
    hi! link NERDTreeCWD Comment
    hi! link NERDTreeDirSlash Directory
    hi YcmInverse ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link HarpyFileNotFound Error
    hi HarpySelectedFile ctermfg=28 ctermbg=194 cterm=NONE
    hi GenericRedPop ctermfg=160 ctermbg=217 cterm=bold,italic
    hi GenericGreenPop ctermfg=28 ctermbg=194 cterm=bold,italic
    hi GenericYellowPop ctermfg=100 ctermbg=229 cterm=bold,italic
    hi GenericBluePop ctermfg=26 ctermbg=153 cterm=bold,italic
    hi GenericMagentaPop ctermfg=91 ctermbg=255 cterm=bold,italic
    hi GenericCyanPop ctermfg=65 ctermbg=254 cterm=bold,italic
    if !s:italics
      hi Folded cterm=NONE
      hi StatusLine cterm=NONE
      hi StatusLineTerm cterm=NONE
      hi WarningMsg cterm=NONE
      hi WildMenu cterm=NONE
      hi Comment cterm=NONE
      hi Error cterm=NONE
      hi YcmInverse cterm=NONE
      hi GenericRedPop cterm=bold
      hi GenericGreenPop cterm=bold
      hi GenericYellowPop cterm=bold
      hi GenericBluePop cterm=bold
      hi GenericMagentaPop cterm=bold
      hi GenericCyanPop cterm=bold
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'enough_colors_opt_transp_bg', 0)
      hi Normal ctermfg=White ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=White ctermbg=Black cterm=NONE
      hi Terminal ctermfg=White ctermbg=Black cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=White ctermbg=Black cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi CursorLineNr ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=White ctermbg=Black cterm=reverse
    hi DiffChange ctermfg=White ctermbg=Black cterm=reverse
    hi DiffDelete ctermfg=White ctermbg=Black cterm=reverse
    hi DiffText ctermfg=White ctermbg=Black cterm=bold,reverse
    hi Directory ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=White ctermbg=Black cterm=NONE
    hi Folded ctermfg=LightMagenta ctermbg=DarkMagenta cterm=italic
    hi IncSearch ctermfg=LightGreen ctermbg=DarkGreen cterm=NONE
    hi LineNr ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=White ctermbg=Black cterm=NONE
    hi ModeMsg ctermfg=White ctermbg=Black cterm=NONE
    hi MoreMsg ctermfg=White ctermbg=Black cterm=NONE
    hi NonText ctermfg=White ctermbg=Black cterm=NONE
    hi Pmenu ctermfg=White ctermbg=DarkGrey cterm=NONE
    hi PmenuSbar ctermfg=White ctermbg=Black cterm=NONE
    hi PmenuSel ctermfg=LightYellow ctermbg=DarkYellow cterm=NONE
    hi PmenuThumb ctermfg=White ctermbg=Black cterm=NONE
    hi Question ctermfg=White ctermbg=Black cterm=NONE
    hi Search ctermfg=LightYellow ctermbg=DarkYellow cterm=NONE
    hi SignColumn ctermfg=White ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=White ctermbg=Black cterm=NONE
    hi SpellBad ctermfg=White ctermbg=Black cterm=NONE
    hi SpellCap ctermfg=White ctermbg=Black cterm=NONE
    hi SpellLocal ctermfg=White ctermbg=Black cterm=NONE
    hi SpellRare ctermfg=White ctermbg=Black cterm=reverse
    hi StatusLine ctermfg=LightBlue ctermbg=DarkBlue cterm=NONE
    hi StatusLineNC ctermfg=LightGrey ctermbg=DarkBlue cterm=NONE
    hi StatusLineTerm ctermfg=LightGreen ctermbg=DarkGreen cterm=NONE
    hi StatusLineTermNC ctermfg=LightGrey ctermbg=DarkGreen cterm=NONE
    hi TabLine ctermfg=White ctermbg=Black cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Black cterm=NONE
    hi Title ctermfg=White ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Visual ctermfg=LightCyan ctermbg=DarkCyan cterm=NONE
    hi VisualNOS ctermfg=LightCyan ctermbg=DarkCyan cterm=NONE
    hi WarningMsg ctermfg=LightYellow ctermbg=NONE cterm=italic
    hi WildMenu ctermfg=LightYellow ctermbg=DarkYellow cterm=NONE
    hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
    hi Constant ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi Error ctermfg=LightRed ctermbg=NONE cterm=italic
    hi Identifier ctermfg=White ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi Statement ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi Operator ctermfg=White ctermbg=NONE cterm=NONE
    hi Special ctermfg=White ctermbg=NONE cterm=NONE
    hi String ctermfg=LightMagenta ctermbg=NONE cterm=NONE
    hi Todo ctermfg=White ctermbg=NONE cterm=NONE
    hi Type ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=White ctermbg=NONE cterm=underline
    hi! link Quote String
    hi! link CursorColumn CursorLine
    hi! link Number Constant
    hi! link ErrorMsg Error
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
    hi! link luaTable Normal
    hi! link jsonKeyword Normal
    hi! link jsonQuote Normal
    hi! link jsonString Normal
    hi! link htmlTag Keyword
    hi! link htmlEndTag Keyword
    hi NERDTreeExecFile ctermfg=LightMagenta ctermbg=NONE cterm=NONE
    hi! link NERDTreeCWD Comment
    hi! link NERDTreeDirSlash Directory
    hi YcmInverse ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link HarpyFileNotFound Error
    hi HarpySelectedFile ctermfg=LightGreen ctermbg=DarkGreen cterm=NONE
    hi GenericRedPop ctermfg=LightRed ctermbg=DarkRed cterm=bold,italic
    hi GenericGreenPop ctermfg=LightGreen ctermbg=DarkGreen cterm=bold,italic
    hi GenericYellowPop ctermfg=LightYellow ctermbg=DarkYellow cterm=bold,italic
    hi GenericBluePop ctermfg=LightBlue ctermbg=DarkBlue cterm=bold,italic
    hi GenericMagentaPop ctermfg=LightMagenta ctermbg=DarkMagenta cterm=bold,italic
    hi GenericCyanPop ctermfg=LightCyan ctermbg=DarkCyan cterm=bold,italic
    if !s:italics
      hi Folded cterm=NONE
      hi WarningMsg cterm=NONE
      hi Comment cterm=NONE
      hi Error cterm=NONE
      hi YcmInverse cterm=NONE
      hi GenericRedPop cterm=bold
      hi GenericGreenPop cterm=bold
      hi GenericYellowPop cterm=bold
      hi GenericBluePop cterm=bold
      hi GenericMagentaPop cterm=bold
      hi GenericCyanPop cterm=bold
    endif
  else
    " Light background
    if get(g:, 'enough_colors_opt_transp_bg', 0)
      hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=White ctermbg=Black cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi CursorLineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=White ctermbg=NONE cterm=reverse
    hi DiffChange ctermfg=White ctermbg=NONE cterm=reverse
    hi DiffDelete ctermfg=White ctermbg=NONE cterm=reverse
    hi DiffText ctermfg=White ctermbg=NONE cterm=bold,reverse
    hi Directory ctermfg=DarkBlue ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=DarkGrey ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=White ctermbg=Black cterm=NONE
    hi Folded ctermfg=DarkMagenta ctermbg=LightMagenta cterm=italic
    hi IncSearch ctermfg=DarkGreen ctermbg=LightGreen cterm=NONE
    hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
    hi ModeMsg ctermfg=Black ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=Black ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=Black ctermbg=NONE cterm=NONE
    hi NonText ctermfg=Black ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi PmenuSbar ctermfg=Black ctermbg=NONE cterm=NONE
    hi PmenuSel ctermfg=DarkYellow ctermbg=LightYellow cterm=NONE
    hi PmenuThumb ctermfg=Black ctermbg=NONE cterm=NONE
    hi Question ctermfg=Black ctermbg=NONE cterm=NONE
    hi Search ctermfg=DarkYellow ctermbg=LightYellow cterm=NONE
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=Black ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=Black ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=Black ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=Black ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=Black ctermbg=NONE cterm=reverse
    hi StatusLine ctermfg=DarkBlue ctermbg=LightBlue cterm=italic
    hi StatusLineNC ctermfg=DarkGrey ctermbg=LightBlue cterm=NONE
    hi StatusLineTerm ctermfg=DarkGreen ctermbg=LightGreen cterm=italic
    hi StatusLineTermNC ctermfg=DarkGrey ctermbg=LightGreen cterm=NONE
    hi TabLine ctermfg=Black ctermbg=NONE cterm=NONE
    hi TabLineFill ctermfg=Black ctermbg=NONE cterm=NONE
    hi TabLineSel ctermfg=Black ctermbg=NONE cterm=NONE
    hi Title ctermfg=Black ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=DarkGrey ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=LightCyan cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=LightCyan cterm=NONE
    hi WarningMsg ctermfg=DarkYellow ctermbg=NONE cterm=italic
    hi WildMenu ctermfg=DarkYellow ctermbg=LightYellow cterm=italic
    hi Comment ctermfg=DarkGrey ctermbg=NONE cterm=italic
    hi Constant ctermfg=DarkBlue ctermbg=NONE cterm=NONE
    hi Error ctermfg=DarkRed ctermbg=NONE cterm=italic
    hi Identifier ctermfg=Black ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=Black ctermbg=NONE cterm=NONE
    hi Statement ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi Operator ctermfg=Black ctermbg=NONE cterm=NONE
    hi Special ctermfg=Black ctermbg=NONE cterm=NONE
    hi String ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
    hi Todo ctermfg=Black ctermbg=NONE cterm=NONE
    hi Type ctermfg=DarkRed ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=Black ctermbg=NONE cterm=underline
    hi! link Quote String
    hi! link CursorColumn CursorLine
    hi! link Number Constant
    hi! link ErrorMsg Error
    hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi ToolbarButton ctermfg=Black ctermbg=LightGrey cterm=bold
    hi! link luaTable Normal
    hi! link jsonKeyword Normal
    hi! link jsonQuote Normal
    hi! link jsonString Normal
    hi! link htmlTag Keyword
    hi! link htmlEndTag Keyword
    hi NERDTreeExecFile ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
    hi! link NERDTreeCWD Comment
    hi! link NERDTreeDirSlash Directory
    hi YcmInverse ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link HarpyFileNotFound Error
    hi HarpySelectedFile ctermfg=DarkGreen ctermbg=LightGreen cterm=NONE
    hi GenericRedPop ctermfg=DarkRed ctermbg=LightRed cterm=bold,italic
    hi GenericGreenPop ctermfg=DarkGreen ctermbg=LightGreen cterm=bold,italic
    hi GenericYellowPop ctermfg=DarkYellow ctermbg=LightYellow cterm=bold,italic
    hi GenericBluePop ctermfg=DarkBlue ctermbg=LightBlue cterm=bold,italic
    hi GenericMagentaPop ctermfg=DarkMagenta ctermbg=LightMagenta cterm=bold,italic
    hi GenericCyanPop ctermfg=DarkCyan ctermbg=LightCyan cterm=bold,italic
    if !s:italics
      hi Folded cterm=NONE
      hi StatusLine cterm=NONE
      hi StatusLineTerm cterm=NONE
      hi WarningMsg cterm=NONE
      hi WildMenu cterm=NONE
      hi Comment cterm=NONE
      hi Error cterm=NONE
      hi YcmInverse cterm=NONE
      hi GenericRedPop cterm=bold
      hi GenericGreenPop cterm=bold
      hi GenericYellowPop cterm=bold
      hi GenericBluePop cterm=bold
      hi GenericMagentaPop cterm=bold
      hi GenericCyanPop cterm=bold
    endif
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black                rgb( 30,  30,  30)   ~          Black
" Color: red                  rgb( 45,  35,  35)   ~          DarkRed
" Color: green                rgb( 35,  45,  35)   ~          DarkGreen
" Color: yellow               rgb( 45,  45,  35)   ~          DarkYellow
" Color: blue                 rgb( 35,  35,  45)   ~          DarkBlue
" Color: magenta              rgb( 45,  35,  45)   ~          DarkMagenta
" Color: cyan                 rgb( 35,  40,  40)   ~          DarkCyan
" Color: lightgrey            rgb(100, 100, 100)   ~          LightGrey
" Color: brightblack          rgb( 40,  40,  40)   ~          DarkGrey
" Color: brightred            rgb(180,  90,  90)   ~          LightRed
" Color: brightgreen          rgb(110, 180, 110)   ~          LightGreen
" Color: brightyellow         rgb(180, 140,  90)   ~          LightYellow
" Color: brightblue           rgb(130, 180, 220)   ~          LightBlue
" Color: brightmagenta        rgb(180, 110, 180)   ~          LightMagenta
" Color: brightcyan           rgb(100, 180, 160)   ~          LightCyan
" Color: brightwhite          rgb(190, 190, 190)   ~          White
" Color: t_black              rgb(  0,   0,   0)   0          Black
" Color: t_red                rgb(128,   0,   0)   1          DarkRed
" Color: t_green              rgb(  0, 128,   0)   2          DarkGreen
" Color: t_yellow             rgb(128, 128,   0)   3          DarkYellow
" Color: t_blue               rgb(  0,   0, 128)   4          DarkBlue
" Color: t_magenta            rgb(128,   0, 128)   5          DarkMagenta
" Color: t_cyan               rgb(  0, 128, 128)   6          DarkCyan
" Color: t_lightgrey          rgb(192, 192, 192)   7          LightGrey
" Color: t_brightblack        rgb(128, 128, 128)   8          DarkGrey
" Color: t_brightred          rgb(255,   0,   0)   9          LightRed
" Color: t_brightgreen        rgb(  0, 255,   0)   10         LightGreen
" Color: t_brightyellow       rgb(255, 255,   0)   11         LightYellow
" Color: t_brightblue         rgb(  0,   0, 255)   12         LightBlue
" Color: t_brightmagenta      rgb(255,   0, 255)   13         LightMagenta
" Color: t_brightcyan         rgb(  0, 255, 255)   14         LightCyan
" Color: t_brightwhite        rgb(255, 255, 255)   15         White
" Term colors: t_black t_red t_green t_yellow t_blue t_magenta t_cyan t_lightgrey
" Term colors: t_brightblack t_brightred t_brightgreen t_brightyellow
" Term colors: t_brightblue t_brightmagenta t_brightcyan t_brightwhite
" Background: light
" Color: black                rgb( 40,  40,  40)   ~          Black
" Color: red                  rgb(200,  40,  40)   ~          DarkRed
" Color: green                rgb( 40, 140,  30)   ~          DarkGreen
" Color: yellow               rgb(140, 130,   0)   ~          DarkYellow
" Color: blue                 rgb(  0,  80, 180)   ~          DarkBlue
" Color: magenta              rgb(120,  60, 170)   ~          DarkMagenta
" Color: cyan                 rgb( 80, 140, 120)   ~          DarkCyan
" Color: lightgrey            rgb(240, 240, 240)   ~          LightGrey
" Color: brightblack          rgb(120, 120, 120)   ~          DarkGrey
" Color: brightred            rgb(250, 180, 180)   ~          LightRed
" Color: brightgreen          rgb(200, 240, 200)   ~          LightGreen
" Color: brightyellow         rgb(250, 250, 180)   ~          LightYellow
" Color: brightblue           rgb(200, 220, 240)   ~          LightBlue
" Color: brightmagenta        rgb(250, 235, 250)   ~          LightMagenta
" Color: brightcyan           rgb(210, 230, 240)   ~          LightCyan
" Color: brightwhite          rgb(255, 255, 255)   ~          White
" Color: t_black              rgb(  0,   0,   0)   0          Black
" Color: t_red                rgb(128,   0,   0)   1          DarkRed
" Color: t_green              rgb(  0, 128,   0)   2          DarkGreen
" Color: t_yellow             rgb(128, 128,   0)   3          DarkYellow
" Color: t_blue               rgb(  0,   0, 128)   4          DarkBlue
" Color: t_magenta            rgb(128,   0, 128)   5          DarkMagenta
" Color: t_cyan               rgb(  0, 128, 128)   6          DarkCyan
" Color: t_lightgrey          rgb(192, 192, 192)   7          LightGrey
" Color: t_brightblack        rgb(128, 128, 128)   8          DarkGrey
" Color: t_brightred          rgb(255,   0,   0)   9          LightRed
" Color: t_brightgreen        rgb(  0, 255,   0)   10         LightGreen
" Color: t_brightyellow       rgb(255, 255,   0)   11         LightYellow
" Color: t_brightblue         rgb(  0,   0, 255)   12         LightBlue
" Color: t_brightmagenta      rgb(255,   0, 255)   13         LightMagenta
" Color: t_brightcyan         rgb(  0, 255, 255)   14         LightCyan
" Color: t_brightwhite        rgb(255, 255, 255)   15         White
" Term colors: t_black t_red t_green t_yellow t_blue t_magenta t_cyan t_lightgrey
" Term colors: t_brightblack t_brightred t_brightgreen t_brightyellow
" Term colors: t_brightblue t_brightmagenta t_brightcyan t_brightwhite
" vim: et ts=8 sw=2 sts=2
